version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - .:/app  
    command: ["npm", "run", "dev"]  

